# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [16.x, 18.x, 20.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies ${{ matrix.node-version }}
        run: npm ci
      - name: Build ${{ matrix.node-version }}
        if: matrix.node-version == '18.x' || matrix.node-version == '20.x'
        run: npm run build --if-present
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
      - name: Run tests ${{ matrix.node-version }}
        if: matrix.node-version == '18.x' || matrix.node-version == '20.x'
        run: npm run test
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
      - name: Build ${{ matrix.node-version }}
        if: matrix.node-version == '16.x'
        run: npm run build --if-present
      - name: Run tests ${{ matrix.node-version }}
        if: matrix.node-version == '16.x'
        run: npm run test
